name: Cypress Single Test on Windows

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci
        working-directory: mi-proyecto-cypress
        shell: powershell

      # 4️⃣ Depuración: listar los tests
      - name: List e2e test files
        run: dir mi-proyecto-cypress\e2e\1-getting-started\PRUEBAS
        shell: powershell

      # 5️⃣ Ejecutar solo el test específico
      - name: Run Cypress test
        run: npx cypress run --spec e2e/1-getting-started/PRUEBAS/login.cy.js
        working-directory: mi-proyecto-cypress
        shell: powershell

      # 6️⃣ Subir screenshots y videos como artifacts
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: mi-proyecto-cypress\cypress\screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: mi-proyecto-cypress\cypress\videos
