name: Run Cypress Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run specific Cypress test
        uses: cypress-io/github-action@v6.5.0
        with:
          start: npx cypress run --spec "mi-proyecto-cypress\1-getting-started\PRUEBAS\login.cy.js"
          record: false
