name: Ejecutar test único en Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: windows-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci
        working-directory: mi-proyecto-cypress
        shell: powershell

      - name: Verificar archivos de prueba
        run: dir mi-proyecto-cypress\e2e\1-getting-started\PRUEBAS
        shell: powershell

      - name: Ejecutar test de Cypress
        run: npx cypress run --spec e2e/1-getting-started/PRUEBAS/login.cy.js
        working-directory: mi-proyecto-cypress
        shell: powershell

      - name: Subir capturas de pantalla
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: mi-proyecto-cypress\cypress\screenshots

      - name: Subir videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: mi-proyecto-cypress\cypress\videos
